### PR TITLE
Added math module to SAMD21 variant ICs

### PR DESCRIPTION
**Pull request by iommu**
The module `math` was only being included for SAMD51 MCUs, this patch adds SAMD21 support

### CODE REVIEW

**Comment by robert-hh** [comment]
Thank you for the PR and working with the port. You may also look at my samd_xtend branch, which adds more functionality to the port and has a minor fixes.
Actually leaving the math module out was intentional. The math module increase the flash size by 13k. But wanted to keep ~20k free for things like including frozen bytecode libs, or just a little bit more headroom for source code level debugging.  
Math can be included any time, once there is less need for debugging. Or maybe I could split the math module up. Which specific math funcions do you use/need?
P.S.: Sorry for answering tardy. I did not expect a PR to this branch, even if I should have received a notification.

**Comment by robert-hh** [comment]
It's 8k for the basic math module, not 13k, a little bit better than assumed. I could as well set the file system size to 56k instead of 64k, if needed. Some boards have additional flash, which can be used for a file system. But the driver for that needs flash itself, about 3k.

**Comment by iommu** [comment]
Hmm I see the issue, In specific I needed the log func

**Comment by robert-hh** [comment]
I looked into the code, and it cannot be split in an easy way. But since you made your own firmware, you can add math. That's why I kept the setting visible in mpconfigmcu.h.

**Comment by robert-hh** [comment]
I added math for the SAMD21 family, and two new methods as well for both families: 

`adc.read_timed_into(buffer, freq)`
with freq = 1 Hz to 200kHz for SAMD21 and 1 Hz to 1MHz for SAMD51, depending on average and bits setting.
`dac.write_timed(buffer, freq [, count])`
with freq = 1 Hz to 100kHz for SAMD21 and 1Hz 500kHz for SAMD51, and count in the range 1 to 2**30.

**Pull request closed without merging**
